#workflow名称
name: Build images(Multi architecture)
# 触发条件
on:
#github页面手动触发
  workflow_dispatch: 
    inputs:
      source_image:
        description: 'source image name'
        required: true
        default: 'nginx:1.25-alpine'
      new_image:
        description: 'new image name'
        required: true
        default: 'registry.cn-beijing.aliyuncs.com/gitosc/nginx:1.25-alpine'

jobs:
  build-image:
    #运行的环境  
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      # 拉取代码，同时获取tag，如果获取不到则默认值为master
      - uses: actions/checkout@v3
      
     # Docker配置多平台环境
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2  
        
      # 登录镜像仓库
      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}   
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ inputs.source_image }}
            ${{ inputs.new_image }}
            
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64

